template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: python_repo_jfp_example
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }}
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }}
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: python_buildinfo_jfp_example
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt

pipelines:
  - name: python_pipeline_jfp_example
    steps:
      - name: python_build_step
        type: Bash
        configuration:
          integrations:
            - name: demoArt  # required
            - name: demoArt_password
          inputResources:
            - name: python_repo_jfp_example         # required
          outputResources:
            - name: python_buildinfo_jfp_example         # required
        execution:
          onExecute:
            - echo $int_demoArt_password_artifactory_password
            - pushd $res_python_repo_jfp_example_resourcePath
            - ./create-pypirc.sh
            - pip install -r requirements.txt
            # Configure Artifactory instance with JFrog CLI
            - jfrog rt config rt-server-1 --url $res_demoArt_url --user $res_demoArt_user --apikey $res_demoArt_apikey
            - python setup.py sdist upload -r local
            - python setup.py bdist_wheel upload -r local
            # Collect build environment variables and build tools information using JFrog CLI
            - jfrog rt bce pipelines-python-sample $run_number
            # Publish build information to Artifactory
            - jfrog rt bp pipelines-python-sample $run_number
            - write_output python_buildinfo_jfp_example buildName=pipelines-python-sample buildNumber=$run_number
            - popd
